version: "2.1"

services:   
   sonarr:
      image: linuxserver/sonarr
      container_name: sonarr
      environment:
         - PUID=1000
         - PGID=1000
         - TZ=
         - UMASK_SET=022
      volumes:
         - /home/alex/services/sonarr/data:/config
         - /home/alex/services/sonarr/tvseries:/tv
         - /home/alex/services/sonarr/downloadclient-downloads:/downloads
      ports:
         - "8989:8989"
      restart: unless-stopped
