version: "3.1"

services: 
   db:
      image: postgres
      restart: unless-stopped
      env_file:
         - database.env
      ports: 
         - "5432:5432"
      volumes:
         - database-data:/var/lib/postgresql/data/
      networks: 
         - db_net


   pgadmin:
      image: dpage/pgadmin4
      depends_on:
         - db
      restart: unless-stopped
      env_file:
         - pgadmin.env
      ports: 
         - "8181:80"
      networks:
         - db_net

volumes:
   database-data:

networks:
   db_net:
